stack: jussi/todo
description: Todo-app bundle, all required services within the stack
version: 0.2.3

services:
  mongo:
    image: mongo:3.2
    instances: 3
    stateful: true
    command: --replSet kontena --smallfiles
    health_check:
      protocol: tcp
      port: 27017
    hooks:
      post_start:
        - cmd: sleep 10
          name: sleep
          instances: 3
          oneshot: true
        - cmd: mongo --eval "printjson(rs.initiate());"
          name: rs_initiate
          instances: 3
          oneshot: true
        - cmd: mongo --eval "printjson(rs.add('mongo-1'))"
          name: rs_add2
          instances: 3
          oneshot: true
        - cmd: mongo --eval "printjson(rs.add('mongo-2'))"
          name: rs_add3
          instances: 3
          oneshot: true

  web:
    image: jnummelin/todo-example:${DRONE_TAG}
    instances: 3
    deploy:
      wait_for_port: 9292
      min_health: 0.8
    links:
      - infra/lb-external
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo-1:27017,mongo-2:27017,mongo-3:27017/todo_production
      - KONTENA_LB_VIRTUAL_HOSTS=todo-app.kontena.io
      - KONTENA_LB_INTERNAL_PORT=9292
    command: bundle exec puma -p 9292 -e production
    health_check:
      protocol: http
      uri: /todos
      initial_delay: 60
      interval: 60
      port: 9292
